feat: support reload apisix runnning on bare metal
api7/cloud-cli pull request #62
Opened 2022-10-21 06:35 UTC by tokers

Signed-off-by: tokers <zchao1995@gmail.com>

2022-10-21 06:54 UTC, mscb402 approved these changes

2022-10-21 07:40 UTC, nic-6443 requested changes
The functionality implemented by this PR may not work as the new configuration will be saved in a brand new file, but apisix reload will only read the configuration file that is already in use.
https://github.com/api7/cloud-cli/blob/1db92346d8f7e2fe221563568e70d6fe0ed054a3/cmd/deploy/bare.go#L96
https://github.com/api7/cloud-cli/blob/a84385389ebe88439960fee492192afdfb3dd54a/internal/apisix/config_handler.go#L52

2022-10-21 09:35 UTC, tokers commented
> The functionality implemented by this PR may not work as the new configuration will be saved in a brand new file, but apisix reload will only read the configuration file that is already in use.
> 
> https://github.com/api7/cloud-cli/blob/1db92346d8f7e2fe221563568e70d6fe0ed054a3/cmd/deploy/bare.go#L96
> 
> 
> https://github.com/api7/cloud-cli/blob/a84385389ebe88439960fee492192afdfb3dd54a/internal/apisix/config_handler.go#L52

Fair enough. I'll try to solve it.

2022-10-21 11:45 UTC, Hazel6869 approved these changes

2022-10-24 02:53 UTC, nic-6443 approved these changes

2022-10-24 03:24 UTC, merged